
name: Python package syntax check

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        #python-version: ["3.9", "3.10", "3.11"]
        python-version: ["3.11"]

    steps:
    - uses: actions/checkout@v3
    - name: Install dependencies
      run: |
        make
        . venv/bin/activate
        pip install flake8 pytest
    - name: Lint with flake8
      run: |
        . venv/bin/activate
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

