# uses https://github.com/marketplace/actions/create-release

name: Release Multiplatform Pex

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

    #tags:
    #- '*'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.11
      uses: actions/setup-python@v3
      with:
        python-version: '3.11'
    - name: Install dependencies
      run: |
        make
    - name: Create multiplatform PEX
      run: |
        echo "Python versions in runner:"
        ls -l /opt/hostedtoolcache/Python/
        for d in /opt/hostedtoolcache/Python/* ; do export PATH=$PATH:$d/x64/bin ; done
        echo "Python versions found:"
        which -a python3
        pip install pex
        echo "Pex interpreter paths"
        pex3 interpreter inspect --interpreter-constraint "CPython>=3.9" --verbose --indent 4 > pex3.output
        cat pex3.output | jq ".path"
        make pex-mp
        ls -lrth | grep kafkatop
#    - uses: ncipollo/release-action@v1
#      with:
#        artifacts: "release.tar.gz,foo/*.txt"
#        bodyFile: "body.md"
